version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile.backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - kafka
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
    ports:
      - "3000:3000"
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis:6
  kafka:
    image: confluentinc/cp-kafka:latest
