name: AI Platform CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 */6 * * *'  # Added scheduled runs
  workflow_dispatch:        # Added manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Run tests
      run: |
        python -m pytest tests/ --cov=ai_collaborative_platform --cov-report=xml -v
    
    - name: Upload coverage
      uses: codecov/codecov-action@v2

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort
    
    - name: Run linters
      run: |
        flake8 ai_collaborative_platform
        black --check ai_collaborative_platform
        isort --check-only ai_collaborative_platform

  integrate:
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Verify data structure
      run: python scripts/verify_data_structure.py
    
    - name: Validate exports
      run: python scripts/validate_exports.py
    
    - name: Sync directories
      run: python scripts/sync_data_dirs.py
    
    - name: Create status badge
      run: |
        echo "[![Integration Status](https://github.com/${{ github.repository }}/workflows/AI%20Platform%20CI/CD/badge.svg)](https://github.com/${{ github.repository }}/actions)" >> README.md 